### PR TITLE
Update Holmes Fabric Options en.md

### PR DESCRIPTION
**Pull request by bobgeorgethe3rd**
-Added More Info to existing options
-Added recommendations to existing options
-Added Interfacing section <- Generally you do need interfacing even with a thick material.
-Added Bill Insert Material

### CODE REVIEW

**Comment by bobgeorgethe3rd** [comment]
I am not 100 on the interfacing section. I may tweak it as generally you need interfacing regardless of thickness of fabric.

**Comment by joostdecock** [comment]
Same remark as #265 about the title

**Comment by darigovresearch** [comment]
Am assuming the same goes for this pull request as you mentioned here - https://github.com/freesewing/markdown/pull/265#issuecomment-894654921

**Comment by joostdecock** [comment]
You assume right @darigovresearch  :)

**Pull request merged**
