### PR TITLE
Draft 1 of Instructions for Holmes en.md

### PR DESCRIPTION
**Pull request by bobgeorgethe3rd**
Draft 1
What needs to be checked.
- Spell and Grammar Check
- Proof reading.
- Term/Name updates to match freesewing 
- Glossary Definitions may need tweaking
- Whipstitch might be better refered to as Fell stitch.

### CODE REVIEW

**Comment by joostdecock** [comment]
Not sure whether you're still working on this, but to avoid confusion, I've converted this to a draft.
When you're ready, or would like a review, just let us know in the comments :)

**Comment by bobgeorgethe3rd** [comment]
It's mostly done. I am planning to look into the draft of Holmes and add some sliders for fit and style so it may still need updating for that. But really the only problem I forsee is if I end up adding the extra ear flaps which is a simple addition/change.

**Comment by darigovresearch** [comment]
@bobgeorgethe3rd have you managed to take a look at the above in the meantime since you last posted?

**Comment by bobgeorgethe3rd** [comment]
I know what I would do but I haven't manage to get the Holmes Pattern installed properly to do it. I've been busy working on some new patterns but it is on my list to do after pattern testing. I couldn't get the gore macro to install and I had other things that need doing at the time. If I can get the macro running then I can add the sliders really easily.

**Comment by bobgeorgethe3rd** [comment]
Taken it out of draft. It's going to be hot minute till I get back roudn to the pattern and these instructions are good for current version.

**Pull request merged**
