### PR TITLE
Update Holmes Cutting en.md

### PR DESCRIPTION
**Pull request by bobgeorgethe3rd**
-Added how to cut gore pattern piece
-Updated Cutting list. Ear flaps are generally cut just from the main fabric but left the option for lining. This may need to be updated in the instructions
-Added Bill insert cutting.
-Added Optional Fabric ties
-Added Note about using nett patterns for a more precise sew.
-Added Warning about making a mock-up with the gore pieces first. The pattern doesn't draft with any ease options and it sort of needs some . I plan to look into adding more options for Holmes but either way this is useful if it is the first time making it for someone. 

Changes still needed
-Update to termonology to align with free sewing. I may change the naming of some of the pieces as  gore should be crown, ear should be ear flap. Visor can be bill but visor still works.

### CODE REVIEW

**Comment by joostdecock** [comment]
Note that you need to keep the `title:` prefix in the frontmatter:

```
---
title: Your title here
---

bla bla
```

**Comment by darigovresearch** [comment]
Believe the title prefix has been fixed. @joostdecock is there anything else that is required for this pull request to be merged?

**Comment by darigovresearch** [comment]
@bobgeorgethe3rd do you wish to make your remaining changes in this pull request or will you open an issue & address those changes in a later pull request?

**Comment by joostdecock** [comment]
No, I think we're good. But I've somewhat put a pin in this because I'd like to have a discussion in tonight's contributor call on how to synchronize markdown changes between the [2022 project](https://github.com/freesewing/freesewing/discussions/1210) where markdown content is folded into out monorepo

**Comment by darigovresearch** [comment]
@joostdecock thanks for the update, looking forward to see what is decided after the call!

**Comment by joostdecock** [comment]
Merging this now because we didn't get around to that, and I feel we'd create too big a backlog if we stall any longer

**Pull request merged**
