### PR TITLE
Add Simon by Stefan showcase

### LINKED ISSUE #633: Create Simon showcase from Discord post
- Content: https://discordapp.com/channels/698854858052075530/698854858496802868/767718513418043393
- Howto: https://freesewing.dev/editors/showcase/
- Permission: Granted by Stefan on discord

### PR DESCRIPTION
**Pull request by ElenaFdR**
Closes [#633](https://github.com/freesewing/freesewing/issues/633).

### CODE REVIEW

**Comment by ElenaFdR** [comment]
I have one question: is my author name my Github or my Discord handle? They're not the same.

**Comment by joostdecock** [comment]
The showcase author links to the freesewing user's profile page. So it's the freesewing username.

Eg: https://freesewing.org/showcase/albert-by-wouter/  where the author is `wouter.vdub` which will link to https://freesewing.org/users/wouter.vdub

**Comment by joostdecock** [comment]
Merging this/these as-is for I'd rather have the showcase added than trip over the author.

The idea (in general) is that:

 - blog posts: author is the freesewing username of the person who wrote the post
 - showcase posts: author is the freesewing username of the person who made the showcased items

It's because they use the same template under the hood, but it's perhaps worth re-visiting as it's often not easy to know what people's username is on the site, and people are allowed to change their username, which would break existing links.

**Comment by ElenaFdR** [comment]
Thanks for the clarification! What about adding this to showcase issue template, so it would contain:

- content
- how to
- permission
- ask user for their FreeSewing username

**Comment by joostdecock** [comment]
Good idea: https://github.com/freesewing/freesewing/issues/636

**Pull request merged**
